
<?php
/**
* [ Panicode v1.0 ] 
* 
* configuration.php
*
* ------------------------------------------------------------ 
* This script was generated by "PaniCode v1.0-2018 Commander"
* Generated date : Mon,08 Oct 2018
* ------------------------------------------------------------
*
* @author Alin Koko Mansuby < alinkokomansuby@gmail.com >
* @version 1.0
* @copyright 2018 alinko.id
*
*
*/

$PANICODE['db']['hostname'] = "localhost";
$PANICODE['db']['username'] = "root";
$PANICODE['db']['password'] = "koko";
$PANICODE['db']['database'] = "panicode";


$PANICODE['site']['base_url'] = "http://workspace.kinal/panicode/";
$PANICODE['site']['base_dir'] = "panicode/";
$PANICODE['site']['admin_dir'] = "panicode/administrator/";

