<?php
/**
* [ Panicode v1.0 ] 
* 
* db-config.panicode.php
*
* ------------------------------------------------------------ 
* This script was generated by "PaniCode v1.0-2018 Commander"
* Generated date : Tue,25 Sep 2018
* ------------------------------------------------------------
*
* @author Alin Koko Mansuby < alinkokomansuby@gmail.com >
* @version 1.0
* @copyright 2018 alinko.id
*
*
*/

// DATABASE CONFIGURATION //

$CONFIG['db']['hostname'] = $PANICODE['db']['hostname'];


$CONFIG['db']['username'] = $PANICODE['db']['username'];


$CONFIG['db']['password'] = $PANICODE['db']['password'];


$CONFIG['db']['database'] = $PANICODE['db']['database'];

// END

// Do connection.

$doconnect = $db->connect($CONFIG['db']);

if(!$doconnect)
{
	echo PHP_EOL;
	echo "Error: Unable to connect to MySQL." . PHP_EOL;
    echo "Debugging errno: " . mysqli_connect_errno() . PHP_EOL;
    echo "Debugging error: " . mysqli_connect_error() . PHP_EOL;
    exit;
}