#!/usr/bin/php

<?php

#require_once(__DIR__.'/autoloader.php');
require_once(__DIR__.'/pc_command/Template.php');

Class PaniCode {
	public static $select;
	public static $menulist = ['1' => 'Modules',
							   '2' => 'Classes',
							   '3' => 'Config',
							   '4' => 'Files'];

    public function __construct()
    {
    	if(substr(PHP_OS,0,3)  != 'nix')
    	{
    		die('This supported for linux system only.');
    	}
    }
	public function panic_now()
	{
		self::banner();
		self::menu();
		self::ask('Select');
		self::action();
	}
	public function colors($type=1)
	{
		if($type != 0)
		{
		$x="\033[1;3{$type}m";
		}else{
		$x="\033[0m";
		}
		return $x;
	}
	public function banner()
	{
@system('clear');
print 
"
".self::colors(7)." __________               .__".self::colors(1)."_________            .___ ".self::colors(3)."For   ".self::colors(0)."  
".self::colors(7)." \______   \_____    ____ |__".self::colors(1)."\_   ___ \  ____   __| _/____ ".self::colors(2)."Fast".self::colors(0)."
".self::colors(7)."  |     ___/\__  \  /    \|  ".self::colors(1)."/    \  \/ /  _ \ / __ |/ __ \ 
".self::colors(7)."  |    |     / __ \|   |  \  ".self::colors(1)."\     \___(  <_> ) /_/ \  ___/  ".self::colors(4)."Project.".self::colors(0)."
".self::colors(7)."  |____|    (____  /___|  /__".self::colors(1)."|\______  /\____/\____ |\___  >".self::colors(0)."
".self::colors(7)."                 \/     \/   ".self::colors(1)."        \/            \/    \/ ".self::colors(0)."
  +--------------------------+  +--------------------------+
  | @Version   : 2.0-2018    |  | @Author   : A L I N K O  |
  | @Codename  : EzPz        |  | @Github   : justalinko   |
  +--------------------------+  +--------------------------+

";	
	}
	public function ask($text = 'Select')
	{
		echo PHP_EOL;
		echo "::: PaniCode::$text >>"; self::$select = trim(fgets(STDIN));
	}

	public function menu()
	{
		foreach(self::$menulist as $num=>$menu)
		{
			echo "  [$num]. $menu ".PHP_EOL;
		}
	}
	public function action()
	{
		@$filename=self::$menulist[self::$select];
		if(file_exists(__DIR__.'/pc_command/'.$filename.'.pcmd.php'))
		{
			require_once(__DIR__.'/pc_command/'.$filename.'.pcmd.php');
		}else{
			echo PHP_EOL;
			echo PHP_EOL;
			echo "+-----------------------------------+".PHP_EOL;
			echo "| This Action not found !!!!!!!!!!  |".PHP_EOL;
			echo "+-----------------------------------+".PHP_EOL;
			echo "cz file : $filename not exist !".PHP_EOL;
			exit;
		}
	}
}



PaniCode::panic_now();