<?php
/**
* [ Panicode v1.0 ] 
* 
* crud_panicode.php
*
* ------------------------------------------------------------ 
* This script was generated by "PaniCode v1.0-2018 Commander"
* Generated date : Tue,25 Sep 2018
* ------------------------------------------------------------
*
* @author Alin Koko Mansuby < alinkokomansuby@gmail.com >
* @version 1.0
* @copyright 2018 alinko.id
*
*
*/

if($CONFIG['url']['m'] == 'all' || $CONFIG['url']['em'])
{


		echo $html->table_open(['class' => 'table'],
			[$html->input('checkbox','select[]',['onclick' => 'select_all(this)']),
			'Nama lengkap',
			'Kelas',
			'Jurusan',
			'Action']);
		$q = $db->multiselect(['data_siswa','data_jurusan','data_kelas'],
			['data_siswa.id_jurusan' => 'data_jurusan.id_jurusan',
			'data_siswa.id_kelas' => 'data_kelas.id_kelas']);
		while($f=$db->fetch($q))
		{

		echo $html->tr([
			$html->input('checkbox','select[]',['onclick' => 'select_all(this)']),
			$f['nama_lengkap'],
			$f['nama_kelas'],
			$f['nama_jurusan'],
			$fedoracss->action('crud_panicode',$f['id_siswa'])]);
		}
		echo $html->tr([$fedoracss->button('danger','hapus terpilih'),'','','','','']);
		echo $html->table_close();
		?>
		
	<?php
}else{

	if($CONFIG['url']['m'] == 'tambah_kelas')
	{
		require $CONFIG['path']['modules'].'crud/tambah_kelas.php';

	}elseif($CONFIG['url']['m'] == 'tambah_jurusan')
	{
		require $CONFIG['path']['modules'].'crud/tambah_jurusan.php';

	}elseif($CONFIG['url']['m'] == 'tambah_siswa')
	{
		require $CONFIG['path']['modules'].'crud/tambah_siswa.php';

	}elseif($CONFIG['url']['m'] == 'edit')
	{
		$q = $db->select_where('data_siswa',['id_siswa' => abs($_GET['id'])]);
		$f = $db->fetch($q);
		?><h3 class="align-center bg-success text-white">Tambah jurusan</h3>
<form method="post">
<table class="table w-100">
	<tr><td>Nama lengkap</td><td><input type="text" name="nama" class="input full" placeholder="Nama lengkap" value="<?=$f['nama_lengkap'];?>"></td></tr>
	<tr><td>Jurusan</td><td>
		<select class="input full" name="jurusan">
			<?php
			$q=$db->select('data_jurusan');
			while($d=$db->fetch($q))
			{
				echo "<option value='".$d['id_jurusan']."'>".$d['nama_jurusan']."</option>";
			}
			?>
		</select>Alin koko Mansuby
	</td></tr>
	<tr><td>Kelas</td><td>
		<select class="input full" name="kelas">
			<?php
			$q=$db->select('data_kelas');
			while($d=$db->fetch($q))
			{
				echo "<option value='".$d['id_kelas']."'>".$d['nama_kelas']."</option>";
			}
			?>
		</select>
	</td></tr>
	<tr><td colspan="2">
		<input type="submit" name="submit" class="btn success block" value="Simpan">
	</td></tr>
</table>
</form>

<?php
if($core->method_post('submit',false,true))
{
	$nama=$core->method_post('nama');
	$jurusan=$core->method_post('jurusan');
	$kelas=$core->method_post('kelas');

	$db->update('data_siswa',['id_kelas' => $kelas,
							 'id_jurusan' => $jurusan,
							 'nama_lengkap' => $nama],
							 ['id_siswa' => abs($_GET['id'])]);
	$core->redirect('?p=crud_panicode&m=all');
}
	}elseif($CONFIG['url']['m'] == 'delete')
	{
		$db->delete('data_siswa',['id_siswa' => abs($_GET['id'])]);

		$core->redirect('?p=crud_panicode&m=all');
	}
}