<?php
/**
* [ Panicode v1.0 ] 
* 
* crud/tambah_jurusan.php
*
* ------------------------------------------------------------ 
* This script was generated by "PaniCode v1.0-2018 Commander"
* Generated date : Tue,25 Sep 2018
* ------------------------------------------------------------
*
* @author Alin Koko Mansuby < alinkokomansuby@gmail.com >
* @version 1.0
* @copyright 2018 alinko.id
*
*
*/

?>
<h3 class="align-center bg-warning text-white">Tambah jurusan</h3>
<form method="post">
<table class="table w-100">
	<tr><td>Jurusan</td><td><input type="text" name="nama_jurusan" class="input full" placeholder="Jurusan"></td></tr>
	<tr><td>Ketua Jurusan</td><td><input type="text" name="ketua_jurusan" class="input full" placeholder="Ketua Jurusan"></td></tr>
	<tr><td colspan="2">
		<input type="submit" name="submit" class="btn warning block" value="Simpan">
	</td></tr>
</table>
</form>
<?php
if($core->method_post('submit',false,true))
{
	$jr=$core->method_post('nama_jurusan');
	$kt=$core->method_post('ketua_jurusan');
	$db->insert('data_jurusan',['',$jr,$kt]);
	$core->redirect('?p=crud_panicode&m=all');
}