<?php
/**
* [ Panicode v1.0 ] 
* 
* crud/tambah_kelas.php
*
* ------------------------------------------------------------ 
* This script was generated by "PaniCode v1.0-2018 Commander"
* Generated date : Tue,25 Sep 2018
* ------------------------------------------------------------
*
* @author Alin Koko Mansuby < alinkokomansuby@gmail.com >
* @version 1.0
* @copyright 2018 alinko.id
*
*
*/
?>
<h3 class="align-center bg-danger text-white">Tambah kelas</h3>
<form method="post">
<table class="table w-100">
	<tr><td>Nama kelas</td><td><input type="text" name="nama_kelas" class="input full" placeholder="Nama kelas"></td></tr>
	<tr><td>Wali kelas</td><td><input type="text" name="wali_kelas" class="input full" placeholder="Wali kelas"></td></tr>
	<tr><td colspan="2">
		<input type="submit" name="submit" class="btn danger block" value="Simpan">
	</td></tr>
</table>
</form>
<?php
if($core->method_post('submit',false,true))
{
	$jr=$core->method_post('nama_kelas');
	$kt=$core->method_post('wali_kelas');
	$db->insert('data_kelas',['',$jr,$kt]);
	$core->redirect('?p=crud_panicode&m=all');
}