<?php
/**
* [ Panicode v1.0 ] 
* 
* crud/tambah_kelas.php
*
* ------------------------------------------------------------ 
* This script was generated by "PaniCode v1.0-2018 Commander"
* Generated date : Tue,25 Sep 2018
* ------------------------------------------------------------
*
* @author Alin Koko Mansuby < alinkokomansuby@gmail.com >
* @version 1.0
* @copyright 2018 alinko.id
*
*
*/
?>
<h3 class="align-center bg-success text-white">Tambah siswa</h3>
<form method="post">
<table class="table w-100">
	<tr><td>Nama lengkap</td><td><input type="text" name="nama" class="input full" placeholder="Nama lengkap"></td></tr>
	<tr><td>Jurusan</td><td>
		<select class="input full" name="jurusan">
			<?php
			$q=$db->select('data_jurusan');
			while($d=$db->fetch($q))
			{
				echo "<option value='".$d['id_jurusan']."'>".$d['nama_jurusan']."</option>";
			}
			?>
		</select>
	</td></tr>
	<tr><td>Kelas</td><td>
		<select class="input full" name="kelas">
			<?php
			$q=$db->select('data_kelas');
			while($d=$db->fetch($q))
			{
				echo "<option value='".$d['id_kelas']."'>".$d['nama_kelas']."</option>";
			}
			?>
		</select>
	</td></tr>
	<tr><td colspan="2">
		<input type="submit" name="submit" class="btn success block" value="Simpan">
	</td></tr>
</table>
</form>
<?php
if($core->method_post('submit',false,true))
{
	$nama=$core->method_post('nama');
	$jurusan=$core->method_post('jurusan');
	$kelas=$core->method_post('kelas');

	$db->insert('data_siswa',['',$kelas,$jurusan,$nama]);
	$core->redirect('?p=crud_panicode&m=all');
}