<?php 
/**
* [ Panicode v1.0 ] 
* 
* 
*
* @author Alin Koko Mansuby < alinkokomansuby@gmail.com >
* @version 1.0
* @copyright 2018 alinko.id
*
*
*/


Class Template extends PaniCode_{
	public function header($filename){
$header = "<?php
/**
* [ Panicode v1.0 ] 
* 
* {$filename}
*
* ------------------------------------------------------------ 
* This script was generated by \"PaniCode v1.0-2018 Commander\"
* Generated date : ".date('D,d M Y')."
* ------------------------------------------------------------
*
* @author Alin Koko Mansuby < alinkokomansuby@gmail.com >
* @version 1.0
* @copyright 2018 alinko.id
*
*
*/
";
return $header;
	}

	public function crud()
	{
		$crud = "
if(\$CONFIG['url']['m'] == 'all' || \$CONFIG['url']['em'])
{

// code here

}else{

if(\$CONFIG['url']['m'] == 'edit')
{

// code here

/** default action **/
if(\$core->method_post('submit',false,true))
{
	\$var = ;

	\$data = ['data' => \$var];
	\$db->update('table_name',\$data);
	\$core->redirect('?all');
}
/** end **/


}elseif(\$CONFIG['url']['m'] == 'delete')
{

// code here


/** default action **/

\$db->delete('table_name',['id' => abs(\$core->method_get('id'))]);
\$core->redirect('?all');

/** end **/


}elseif(\$CONFIG['url']['m'] == 'add')
{

// code here


/** default action **/
if(\$core->method_post('submit',false,true))
{
	\$var = ;

	\$data = ['data' => \$var];
	\$db->insert('table_name',\$data);
	\$core->redirect('?all');
}
/** end **/


}

}

/** end **/
";

		return $crud;
	}
	public function auth()
	{
		$auth="
if(\$CONFIG['url']['em'])
{

// code here

}else{

if(\$CONFIG['url']['m'] == 'login')
{

// code here


/** default authetenticate login code **/

if(\$core->method_post('submit',false,true))
{
	\$username=\$core->method_post('username');
	\$password=\$core->hashm(\$core->method_post('password'),'sha1');

	\$query = \$db->query(\"SELECT * FROM tables_name WHERE username='\$username' AND password='\$password' \");
	\$count = \$db->count_rows(\$query);
	\$data = \$db->fetch(\$query);

	if(\$count > 0)
	{
		\$session_data = [
		'username' => \$data['username'],
		'password' => \$data['password'],
		'PaniCode_session' => TRUE ];

		if(\$core->create_session(\$session_data)){
		
		\$core->redirect('?im-have-session');

		}
	}else{
		echo 'username / password salah ';
	}

}
/** end **/

}elseif(\$CONFIG['url']['m'] == 'register')
{

// code here

}

}
/** end **/
";
return $auth;
	}
	public function emptyClass($class_name)
	{
		$class="Class {$class_name}{

			public function __construct()
			{
				// code here
			}


			public function PaniCode_()
			{
				echo \"Hello world\";
			}

		}";

		return $class;
	}

	public function create_dbconnection($host,$user,$pass,$db)
	{
		$co = "
// DATABASE CONFIGURATION //

\$CONFIG['db']['hostname'] = \"{$host}\";


\$CONFIG['db']['username'] = \"{$user}\";


\$CONFIG['db']['password'] = \"{$pass}\";


\$CONFIG['db']['database'] = \"{$db}\";

// END

// Do connection.

\$doconnect = \$db->connect(\$CONFIG['db']);

if(!\$doconnect)
{
	echo PHP_EOL;
	echo \"Error: Unable to connect to MySQL.\" . PHP_EOL;
    echo \"Debugging errno: \" . mysqli_connect_errno() . PHP_EOL;
    echo \"Debugging error: \" . mysqli_connect_error() . PHP_EOL;
    exit;
}";
return $co;
	}
}


?>