<?php
/**
* [ Panicode v1.0 ] 
* 
* fedoracss_helper.php
*
* ------------------------------------------------------------ 
* This script was generated by "PaniCode v1.0-2018 Commander"
* Generated date : Tue,25 Sep 2018
* ------------------------------------------------------------
*
* @author Alin Koko Mansuby < alinkokomansuby@gmail.com >
* @version 1.0
* @copyright 2018 alinko.id
*
*
*/
Class fedoracss_helper{

	public function alert($type = '',$text = 'PaniCode fedoracss helper.')
	{
		$html='<label class="alert '.$type.'"> '.$text.' </label>';
		return $html;
	}

	public function button($type = '',$text,$property = array())
	{
		$html = "<button ";
		if(is_array($property) && !empty($property))
		{
			foreach($property as $prop=>$val)
			{
				$html.= $prop."='$val' ";
			}
		}
		$html.="class='btn {$type}' > ".$text;
		$html.=" </button>";
		return $html;
	}
	public function action($url,$id)
	{
		$html = "<a href='?p={$url}&m=delete&id={$id}'>Delete</a>|";
		$html.= "<a href='?p={$url}&m=edit&id={$id}'>Edit</a>";
		return $html;
	}
	public function display($type = 'top-center',$content)
	{
		$html ="<div class='container relative'>".PHP_EOL; 
		$html.="<div class='".$type."'>".PHP_EOL;
		$html.=$content.PHP_EOL;
		$html.="</div>";
		$html.= "</div>";
		return $html;
	}

}